In [21]:
import numpy as np

def get_inv(x, M):
    x_inv = 1
    while True:
        if (x*x_inv)%M == 1:
            break
        x_inv += 1
    return x_inv
# 
M = 5 # Must be prime number 
N = 4 # N is a factor of M-1
# Find N_inv
N_inv = get_inv(N, M)
print(f"N_inv = {N_inv}")

# Find smallest possible alpha
alpha = 1
while True:
    is_OK = True
    for k in range(1, N):
        if (alpha**k)%M == 1: # Not Ok 
            is_OK = False
            break
    if (alpha**N)%M != 1: # Not ok 
        is_OK = False

    if is_OK:
        print(f"Found alpha = {alpha}")
        break
    else:
        alpha += 1
# Find alpha_inv 
# Find N_inv
alpha_inv = get_inv(alpha, M)
print(f"alpha_inv = {alpha_inv}")

# Find A, forward transform
A = np.zeros((N, N))
for n in range(N):
    for k in range(N):
        A[k, n] = ( alpha**( (n*k)%N ) )%M
print("NNT forward matrix A: ")
print(A)

# Find B, inverse transform
B = np.zeros((N, N))
for n in range(N):
    for k in range(N):
        B[k, n] = (N_inv * (alpha_inv**( (n*k)%N ))%M) %M
print("NNT inverse matrix B: ")
print(B)

# Verify (B*A)modM = I
print("(B*A)modM: ")
print( np.matmul(B,A) % M )




N_inv = 4
Found alpha = 2
alpha_inv = 3
NNT forward matrix A: 
[[1. 1. 1. 1.]
 [1. 2. 4. 3.]
 [1. 4. 1. 4.]
 [1. 3. 4. 2.]]
NNT inverse matrix B: 
[[4. 4. 4. 4.]
 [4. 2. 1. 3.]
 [4. 1. 4. 1.]
 [4. 3. 1. 2.]]
(B*A)modM: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
